"""init

Revision ID: 5fa34a371479
Revises: 
Create Date: 2024-04-14 20:00:26.527705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa34a371479'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('City',
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('city_id')
    )
    op.create_table('weather_service',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('fio', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='userroleenum'), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('type_of_temperature', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['City.city_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['weather_service.service_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather',
    sa.Column('weather_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('temperature', sa.Integer(), nullable=False),
    sa.Column('wind_value', sa.Integer(), nullable=True),
    sa.Column('wind_direction', sa.String(length=255), nullable=True),
    sa.Column('pressure', sa.Integer(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['City.city_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['weather_service.service_id'], ),
    sa.PrimaryKeyConstraint('weather_id')
    )
    op.create_table('weather_month',
    sa.Column('month_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('max_temp', sa.Integer(), nullable=True),
    sa.Column('min_temp', sa.Integer(), nullable=True),
    sa.Column('average_temp', sa.Integer(), nullable=True),
    sa.Column('average_wind', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['City.city_id'], ),
    sa.PrimaryKeyConstraint('month_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_month')
    op.drop_table('weather')
    op.drop_table('user')
    op.drop_table('weather_service')
    op.drop_table('City')
    # ### end Alembic commands ###
