"""empty message

Revision ID: 6901f2b7b85f
Revises: 74dbe1cf5ce2
Create Date: 2024-01-23 01:18:39.631025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6901f2b7b85f'
down_revision: Union[str, None] = '74dbe1cf5ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'disabled')
    # ### end Alembic commands ###
